---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-auth
  namespace: secrets
spec:
  encryptedData:
    google-api-key: AgCfadlxlirTVCmpaQPWUia9ufYJdsuf5Dc1JNQMEC84UHnr1PTQTvo0Tagajl3FFqANNWc6tBj+zbvam3hn6X7F4G99H92BK2oSnINt491+Nmf6GboP1LNrDXOiPTq18VIy7dv9kSoP9rUx9Pt57+hZlwPeiVHJWYSpq18F2ocCsmx3xquVU2s1FGUVyCohTcTgbb2snSnedzlfBsCbSXSwBnQrp/23m2ZEUcAobGExc+mw1CWQOam/S0DIFWpvhHBckjCdZJcgOXQBC/86LliTwBe5PpKiLzaP/+scZqDlFR6Y6GTjdcP9MsyJaKVZ5nU9wszJGRVGFPxlCkbVITtMkB8sj2eEyHCb1zrpBac38DDtl3ghIB13T7/KPj96pb4yJZkDDtPadywUcPGyresARqNsqkesm4QkmtF9Ifpm0/Wi6Jsp4ohVnJKLxDS4lpeZpa4ACJIIM4iUMaXrgsimM4ydqp1Bl0nni4uLh9nrSTlFWhBfjXGIdeOhvpSolLFqX7pedkcfiky2+4xTCcL0OeIC0HXBXoUmTi86wZwiXYN+0gm3uPbXmX5BB36W7TJX9RnXmmO0/sSXHTrJ+NCKxU2qq/AinkuHMDqHdx8ASqIDTYqZk+/sGlPkBC4wwLbhQ4RPXnmy6qLy1l3EtiarsVaVsB12wgQgXgOKcdhMRpjk8jN3VLpgZOyukpqzFZRDVTGb16V83N6q5ZvO38abSerYwBx5F668LIiRknXFA2p2sb3ofGA=
  template:
    metadata:
      creationTimestamp: null
      name: google-auth
      namespace: secrets
