# To run: 'docker compose up -d', and we will have a container running
# To stop: docker compose down
version: '3'

services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_DB: cannon
      POSTGRES_USER: cannon
      POSTGRES_PASSWORD: cannon
    ports:
      - '5432:5432'

  redis:
    image: 'redis:alpine'
    # command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
