---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-auth
  namespace: postgresql
spec:
  encryptedData:
    postgresql-password: AgChcJwk0sV1jTW/X2y4OzmIyeQgpR+kNQjEMHGNbBO+zJKp0Cl317we1OeViqk7BzRSDaxmeaLS87j9tKlpPJZbd/MVRHXSKPLZb4sUNoQ9G+GDs6dUkRw1TMYlYIdqolVUPUjl5YtTBD2gwVW4E7RyxOCVoVLbGHOoB8kG6UetNNjjRHmB//hHU4R94PX/xITw7FovBPQWTpYeYEsP2G0oFv0OxOvYJJnun1YTxOMb46HWcsZ5reJ1jj45vLJxlRvlUe63/u+RK31SYIuLJ33Y+owGqsusC0U2sEYr6TacGui2ejRweNxAIp6RxtzUG9ui8EqOmlEb9uTNe4C/qDowUeLEFpj53W5YsWouP5Qo4VkEKGfpTklcwpJBwNoSFbQhSWw59/bkUFEfbVSbdnAMKkJE9AabHt81cPTbnnoKR2Lkd/rUqHJbYuqnutvZVQ05rw1xdDOnN3GI1gu8cQ2T9mTPStzcSbE/B2vPLfAPXzh0EVpK93XUozHIgkDB9e96h0dqsYB3/eqHdIQfedpG3bdqWagPSw/qQo9AEO2jYvyGzh7xn0aJa5bjVLhYj743cl/kXMuFuop/NGW7Nz7sNcGmeWvsWFnkrJdgyaze4z/pg+RrLvXvZW9UVGZJ8drfx4rs3c/CqdAfXUSVm0kBgC53XgBxOFlfZZ+96X1CVPFfRN0KHtxm7xJh0p4qtdqs6RkdnFAB9OEV
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-auth
      namespace: postgresql
