name: 'Comment PR'
description: 'Comment on PR, replace if another comment with the same title exists'

inputs:
  github_token:
    description: 'GitHub token'
    required: true
  add:
    description: 'The amount of resources to add'
    required: true
  change:
    description: 'The amount of resources to change'
    required: true
  destroy:
    description: 'The amount of resources to destroy'
    required: true
  run_link:
    description: 'The link to the Terraform Cloud run'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
