apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::384389382109:role/eksctl-postrix-addon-iamserviceaccount-kube-s-Role1-uyVjVbGaAXMc