apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-elasticsearch
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "false"
  # Tags for the EBS volume
  tagSpecification_1: "Name=elasticsearch-persistent-storage"
  tagSpecification_2: "Application=elasticsearch"
  tagSpecification_3: "Component=database"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-kibana
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "false"
  # Tags for the EBS volume
  tagSpecification_1: "Name=kibana-persistent-storage"
  tagSpecification_2: "Application=kibana"
  tagSpecification_3: "Component=database"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
reclaimPolicy: Delete