# Cluster Autoscaler additional RBAC permissions
# This fixes the volumeattachments permission error
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler-additional-permissions
rules:
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch"] 