replicas: 1
postrixImage:
  repository: yuvadius/cannon
  tag: latest
env: prod
containerPort: 8080
ingressPort: 8080
servicePort: 8080
serviceTargetPort: 8080
serviceType: ClusterIP
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
ingress: true