{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ if eq .Release.Namespace "prod" }}{{ printf "%s.postrix.io" .Release.Name }}{{ else }}{{ printf "%s-%s.postrix.io" .Release.Name .Release.Namespace }}{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.ingressPort }}
{{- end }}