{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Add this for automatic redirection of www prefix
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host ~ ^www\.(.+)$) {
        return 301 $scheme://$1$request_uri;
      }
spec:
  ingressClassName: nginx
  rules:
  - host: {{ if eq .Release.Namespace "prod" }}{{ printf "%s.postrix.io" .Release.Name }}{{ else }}{{ printf "%s-%s.postrix.io" .Release.Namespace .Release.Name }}{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.ingressPort }}
  {{- if .Values.ingress.additionalHost }}
  - host: {{ .Values.ingress.additionalHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.ingressPort }}
  {{- end }}
{{- end }}