apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
