repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: autoscaler
    url: https://kubernetes.github.io/autoscaler

environments:
  local: {}
  dev: {}
  prod: {}

releases:
  - name: sealed-secrets
    namespace: sealed-secrets
    chart: bitnami/sealed-secrets
    version: 2.5.9
    labels:
      app: sealed-secrets
    values:
      - ./sealed-secrets/values/defaults.yaml

  - name: ingress-controller
    namespace: ingress-nginx
    chart: ./ingress-controller
    labels:
      app: ingress-controller
    values:
      - ./ingress-controller/values/defaults.yaml

  - name: cluster-autoscaler
    namespace: kube-system
    chart: autoscaler/cluster-autoscaler
    version: 9.46.0
    labels:
      app: cluster-autoscaler
    values:
      - ./cluster-autoscaler/values/defaults.yaml

  - name: elasticsearch
    namespace: elastic
    chart: ./elasticsearch
    labels:
      app: elasticsearch
    values:
      - ./elasticsearch/values/defaults.yaml

  - name: external-dns
    namespace: kube-system
    chart: ./external-dns
    labels:
      app: external-dns
    values:
      - ./external-dns/values/defaults.yaml

  - name: redis
    namespace: redis
    chart: ./redis
    labels:
      app: redis
    values:
      - ./redis/values/defaults.yaml

  - name: joby
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: ./common
    labels:
      app: joby
      group: app
    values:
      - ./joby/values/defaults.yaml
      - ./joby/values/{{ .Environment.Name }}.yaml

  - name: capish
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: ./common
    labels:
      app: capish
      group: app
    values:
      - ./capish/values/defaults.yaml
      - ./capish/values/{{ .Environment.Name }}.yaml

  - name: cannon
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: ./common
    labels:
      app: cannon
      group: app
    values:
      - ./cannon/values/defaults.yaml
      - ./cannon/values/{{ .Environment.Name }}.yaml
