repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

environments:
  local: {}
  dev: {}
  prod: {}

releases:
  - name: external-dns
    namespace: kube-system
    chart: ./external-dns
    labels:
      app: external-dns
    values:
      - ./external-dns/values/{{ .Environment.Name }}.yaml

  - name: ingress-controller
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.11.3"
    labels:
      app: ingress-controller
    values:
      - ./ingress-controller/values/{{ .Environment.Name }}.yaml

  - name: postgresql
    namespace: postgresql
    chart: bitnami/postgresql
    labels:
      app: postgresql
    values:
      - ./postgresql/values/{{ .Environment.Name }}.yaml

  - name: redis
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: bitnami/redis
    labels:
      app: redis
      group: app
    values:
      - ./redis/values/{{ .Environment.Name }}.yaml
  
  # - name: rabbitmq
  #   namespace: "{{ default .Namespace .Environment.Name }}"
  #   chart: bitnami/rabbitmq
  #   labels:
  #     app: rabbitmq
  #   values:
  #     - ./rabbitmq/values/{{ .Environment.Name }}.yaml

  - name: joby
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: ./common
    labels:
      app: joby
      group: app
    values:
      - ./joby/values/{{ .Environment.Name }}.yaml

  - name: capish
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: ./common
    labels:
      app: capish
      group: app
    values:
      - ./capish/values/{{ .Environment.Name }}.yaml