repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: autoscaler
    url: https://kubernetes.github.io/autoscaler
  - name: eks
    url: https://aws.github.io/eks-charts

environments:
  local: {}
  dev: {}
  prod: {}

releases:
  - name: ingress-controller
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.12.1
    labels:
      app: ingress-controller
    values:
      - ./ingress-controller/values/defaults.yaml

  - name: cluster-autoscaler
    namespace: kube-system
    chart: autoscaler/cluster-autoscaler
    version: 9.46.0
    labels:
      app: cluster-autoscaler
    values:
      - ./cluster-autoscaler/values/defaults.yaml

  - name: external-dns
    namespace: kube-system
    chart: ./external-dns
    labels:
      app: external-dns
    values:
      - ./external-dns/values/defaults.yaml

  - name: postgresql
    namespace: postgresql
    chart: bitnami/postgresql
    labels:
      app: postgresql
    values:
      - ./postgresql/values/defaults.yaml

  - name: redis
    namespace: redis
    chart: bitnami/redis
    labels:
      app: redis
    values:
      - ./redis/values/defaults.yaml

  - name: joby
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: ./common
    labels:
      app: joby
      group: app
    values:
      - ./joby/values/defaults.yaml
      - ./joby/values/{{ .Environment.Name }}.yaml

  - name: capish
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: ./common
    labels:
      app: capish
      group: app
    values:
      - ./capish/values/defaults.yaml
      - ./capish/values/{{ .Environment.Name }}.yaml

  - name: cannon
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: ./common
    labels:
      app: cannon
      group: app
    values:
      - ./cannon/values/defaults.yaml
      - ./cannon/values/{{ .Environment.Name }}.yaml
