repositories:
  - name: stable
    url: https://charts.helm.sh/stable

environments:
  local: {}
  dev: {}
  prod: {}

releases:
  - name: redis
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: bitnami/redis
    labels:
      app: redis
    values:
      - ./redis/values/{{ .Environment.Name }}.yaml

  - name: core
    namespace: "{{ default .Namespace .Environment.Name }}"
    chart: ./core
    labels:
      app: core
    values:
      - ./core/values/{{ .Environment.Name }}.yaml