# Requires GCP_SERVICE_ACCOUNT_KEY secret to be passed as an environment variable

name: 'GCP Warm Up'
description: 'Warm up GCP resources for GitHub Actions'
inputs:
  project_id:
    description: 'The GCP project ID'
    required: true
  region:
    description: 'The GCP region'
    required: true
  configure_docker:
    description: 'Whether to configure Docker for Google Artifact Registry'
    default: 'false'
  install_components:
    description: 'What components to install'
  

runs:
  using: 'composite'
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ inputs.project_id }}
        install_components: ${{ inputs.install_components }}

    - name: Configure Docker for Google Artifact Registry
      if: ${{ inputs.configure_docker == 'true' }}
      run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev
      shell: bash