name: 'GCP Warm Up'
description: 'Warm up GCP resources for GitHub Actions'
inputs:
  project_id:
    description: 'The GCP project ID'
    required: true
  region:
    description: 'The GCP region'
    required: true
  configure_docker:
    description: 'Whether to configure Docker for Google Artifact Registry'
    default: 'false'
  install_components:
    description: 'What components to install'
  workload_identity_provider:
    description: 'The workload identity provider'
    required: true
  service_account:
    description: 'The service account email for authentication'
    required: true
  cluster_name:
    description: 'The name of the Kubernetes cluster to authenticate to'
    required: false
    default: ''
  

runs:
  using: 'composite'
  steps:
    - name: Google Authenticate
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        project_id: ${{ inputs.project_id }}
        service_account: ${{ inputs.service_account }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: ${{ inputs.install_components }}

    - name: Configure Docker for Google Artifact Registry
      if: ${{ inputs.configure_docker == 'true' }}
      run: gcloud auth configure-docker ${{ inputs.region }}-docker.pkg.dev
      shell: bash

    - name: Get Credentials
      if: ${{ inputs.cluster_name != '' }}
      run: |
        curl -L https://github.com/roboll/helmfile/releases/download/v0.144.0/helmfile_linux_amd64 -o /usr/local/bin/helmfile
        chmod +x /usr/local/bin/helmfile
        gcloud beta container clusters get-credentials ${{ inputs.cluster_name }} --region ${{ inputs.region }} --project ${{ inputs.project_id }}
      shell: bash