name: 'AWS Warm Up'
description: 'Warm up AWS resources for GitHub Actions'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::384389382109:role/github-actions-role

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name postrix --region us-east-1
      shell: bash

    - name: Verify kubectl access
      run: |
        kubectl get pods -A
      shell: bash

    # - name: Setup helmfile
    #   uses: mamezou-tech/setup-helmfile@v2.0.0
    #   with:
    #     helmfile-version: "v0.168.0"