name: 'AWS Warm Up'
description: 'Warm up AWS resources for GitHub Actions'
inputs:
  role_to_assume:
    description: 'ARN of role to assume'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: ${{ inputs.role_to_assume }}

    # - name: Install kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: 'latest'

    # - name: Update kubeconfig
    #   run: |
    #     aws eks update-kubeconfig --region us-east-1 --name postrix
    #   shell: bash

    # - name: Setup helmfile
    #   uses: mamezou-tech/setup-helmfile@v2.0.0
    #   with:
    #     helmfile-version: "v0.168.0"