name: 'Repo Warm Up'
description: 'Warm up resources for GitHub Actions'

outputs:
  git_hash:
    description: 'The git hash of the current commit'
    value: ${{ steps.get_git_hash.outputs.GIT_HASH }}
  adhoc_namespace:
    description: 'The k8s namespace to deploy your adhoc service to'
    value: ${{ steps.adhoc_namespace.outputs.NAMESPACE }}

runs:
  using: 'composite'
  steps:
    - name: Get Git Hash
      id: get_git_hash
      run: |
        echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get namespace
      id: adhoc_namespace
      run: |
        NAMESPACE=$(echo "${{ github.head_ref || github.ref_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g' | cut -c -30 | sed 's/-*$//')
        echo "NAMESPACE=$NAMESPACE" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install and Build TypeScript Actions
      run: |
        for dir in .github/actions/*/; do
          if [ -f "$dir/package.json" ]; then
            npm --prefix "$dir" install && npm --prefix "$dir" run build
          fi
        done
      shell: bash
