name: 'Repo Warm Up'
description: 'Warm up resources for GitHub Actions'

inputs:
  namespace:
    required: false
    description: 'The namespace to deploy to, defaults to adhoc namespace'

outputs:
  git_hash:
    description: 'The git hash of the current commit'
    value: ${{ steps.git_hash.outputs.git_hash }}
  namespace:
    description: 'The k8s namespace to deploy your service to'
    value: ${{ steps.adhoc_namespace.outputs.namespace }}

runs:
  using: 'composite'
  steps:
    - name: Get Git Hash
      id: git_hash
      run: |
        echo "git_hash=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get namespace
      id: adhoc_namespace
      run: |
        if [ -n "${{ inputs.namespace }}" ]; then
          echo "namespace=${{ inputs.namespace }}" >> $GITHUB_OUTPUT
        else
          namespace=$(echo "${{ github.head_ref || github.ref_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g' | cut -c -30 | sed 's/-*$//')-adhoc
          echo "namespace=$namespace" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.0.1'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
      shell: bash

    - name: Build TypeScript Actions
      run: |
        for dir in .github/actions/*/; do
          if [ -f "$dir/package.json" ] && jq -e '.scripts.build' "$dir/package.json" > /dev/null; then
            echo "Building $dir"
            npm run build --workspace="$dir"
          else
            echo "No build script in $dir, skipping."
          fi
        done
      shell: bash
