apiVersion: v2
name: ingress-controller
description: Custom ingress-nginx deployment with additional TCP services ConfigMap
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: ingress-nginx
    version: "4.12.3"
    repository: "https://kubernetes.github.io/ingress-nginx"