autoDiscovery:
  clusterName: postrix
awsRegion: us-east-1
rbac:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::384389382109:role/postrix-cluster-autoscaler-role
extraArgs:
  scale-down-delay-after-add: 2m
  scale-down-unneeded-time: 2m
  unremovable-node-recheck-timeout: 1m