replicas: 1
image: us-central1-docker.pkg.dev/postrix-development/development-docker/core:latest
env: dev
containerPort: 8000
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
ingress:
  host: "core.dev.postrix.io"