replicas: 1
image: yuvadius/core:latest
env: local
containerPort: 8080
ingressPort: 8080
servicePort: 8080
serviceTargetPort: 8080
serviceType: LoadBalancer
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi