name: Deploy adhoc

on:
  pull_request:

env:
  REGION: us-central1
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: ./.github/actions/gcp-warm-up
      with:
        project_id: postrix-development
        region: ${{ env.REGION }}
        configure_docker: true
        install_components: beta
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/postrix-development/development-docker/${{ env.BRANCH_NAME }}-core:latest ./services/core

    - name: Push Docker image to Google Artifact Registry
      run: |
        docker push $REGION-docker.pkg.dev/postrix-development/development-docker/${{ env.BRANCH_NAME }}-core:latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.BRANCH_NAME }}-core-service \
        --image=$REGION-docker.pkg.dev/postrix-development/development-docker/${{ env.BRANCH_NAME }}-core:latest \
        --region=$REGION \
        --platform=managed \
        --allow-unauthenticated \
        --env-vars-file=./services/core/envs/dev.env \
        --labels=adhoc=true
    
    - name: Get branch url
      id: brach-url
      uses: efiShtain/urlify-string@v1.1
      with:
        string: ${{ env.BRANCH_NAME }}
    
    - name: Map adhoc url to service
      run: |
        if ! gcloud beta run domain-mappings describe --domain ${{ steps.brach-url.outputs.urlified-string  }}-core.dev.postrix.io --region $REGION; then
          gcloud beta run domain-mappings create --service ${{ env.BRANCH_NAME }}-core-service --domain ${{ steps.brach-url.outputs.urlified-string }}-core.dev.postrix.io --region $REGION --quiet
        fi
