name: Build and deploy main to prod/sandbox

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed

jobs:
  build_and_push:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        service: [joby, capish, cannon]
    
    uses: ./.github/workflows/build-and-push.yml
    with:
      service_name: ${{ matrix.service }}
      latest_tag: true
    secrets: inherit

  deploy:
    needs: build_and_push
    
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    strategy:
      matrix:
        environment: [dev, prod]

    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ matrix.environment }}
      namespace: ${{ matrix.environment }}
    secrets: inherit
