name: Build and deploy main to prod/sandbox

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: build-and-deploy
  cancel-in-progress: false

jobs:
  db_migrate:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        environment: [dev, prod]
        db: [cannon]

    uses: ./.github/workflows/db-migrate.yml
    with:
      db: ${{ matrix.db }}
      namespace: ${{ matrix.environment }}
    secrets: inherit

  build_and_push:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        service: [whatsapp, cannon]
    
    uses: ./.github/workflows/build-and-push.yml
    with:
      service_name: ${{ matrix.service }}
      latest_tag: true
    secrets: inherit

  deploy:
    needs: [db_migrate, build_and_push]
    
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    strategy:
      matrix:
        environment: [dev, prod]

    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ matrix.environment }}
      namespace: ${{ matrix.environment }}
    secrets: inherit
