name: Build and deploy adhoc

on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: 'The branch name of the adhoc deployment'
        type: string
  pull_request:

jobs:
  build_and_deploy_adhoc:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        service: [core]

    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: dev
      service_name: ${{ matrix.service }}
      namespace: ${{ inputs.branch_name || github.head_ref || github.ref_name }}
      cluster_name: development
    secrets: inherit

  comment_pr:
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    needs: build_and_deploy_adhoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/repo-warm-up

      - name: Configure AWS credentials
        uses: ./.github/actions/aws-warm-up

      - name: Download Helmfile
        run: |
          wget https://github.com/helmfile/helmfile/releases/download/v0.168.0/helmfile_0.168.0_linux_amd64.tar.gz
          tar xzf helmfile_0.168.0_linux_amd64.tar.gz
          sudo mv helmfile /usr/local/bin/
          helmfile version

      - name: Deploy to Kubernetes
        run: |
          helmfile sync -f kubernetes/helmfile.yaml --environment=dev --namespace=${{ inputs.branch_name || github.head_ref || github.ref_name }} -l group=app

      - name: Comment PR
        uses: ./.github/actions/comment-pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Service URLs"
          message: |
            [Core](${{ inputs.branch_name || github.head_ref || github.ref_name }}-core.dev.postrix.io)
      
