name: Build and deploy adhoc

on:
  workflow_dispatch:
  pull_request:

jobs:
  db_migrate:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        db: [joby, cannon]

    uses: ./.github/workflows/db-migrate.yml
    with:
      db: ${{ matrix.db }}
    secrets: inherit
    
  build_and_push:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        service: [whatsapp, cannon]

    uses: ./.github/workflows/build-and-push.yml
    with:
      service_name: ${{ matrix.service }}
    secrets: inherit

  deploy:
    needs: [db_migrate, build_and_push]

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      namespace_label: adhoc
      comment_pr: ${{ github.event_name != 'workflow_dispatch' }}
    secrets: inherit
