name: Build and deploy service

permissions:
  contents: read
  id-token: write

# Environment variables to be set dynamically later in the workflow
env:
  PROJECT_ID: ''
  IMAGE: ''

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'The environment to deploy to'
        type: string
      service_name:
        required: true
        description: 'The name of the Cloud Run service to deploy'
        type: string
      namespace:
        required: true
        description: 'The k8s namespace of the deployment'
        type: string
      cluster_name:
        required: true
        description: 'The name of the Kubernetes cluster to authenticate to'
        type: string

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Repo Warm Up
      uses: ./.github/actions/repo-warm-up
      id: repo_warm_up

    - name: Configure AWS credentials
      uses: ./.github/actions/aws-warm-up
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Build Docker image
    #   run: |
    #     docker build -t ${{ env.IMAGE }}:${{ steps.repo_warm_up.outputs.git_hash }} -t ${{ env.IMAGE }}:latest ./services/${{ inputs.service_name }}

    # - name: Push Docker image to Google Artifact Registry
    #   run: |
    #     docker push ${{ env.IMAGE }} --all-tags
