name: Build and deploy main to prod/sandbox

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Apply"]
    types:
      - completed
    branches:
      - main
  # Only trigger if there were no changes in terraform
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

concurrency:
  group: build-and-deploy
  cancel-in-progress: false

jobs:
  build_and_push:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion != 'failure' }}
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        service: [joby, capish, cannon]
    
    uses: ./.github/workflows/build-and-push.yml
    with:
      service_name: ${{ matrix.service }}
      latest_tag: true
    secrets: inherit

  deploy:
    needs: build_and_push
    
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    strategy:
      matrix:
        environment: [dev, prod]

    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ matrix.environment }}
      namespace: ${{ matrix.environment }}
    secrets: inherit
