name: Build and deploy adhoc

on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: 'The branch name of the adhoc deployment'
        type: string
  pull_request:

jobs:
  build_and_deploy_adhoc:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        service: [core]

    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: dev
      service_name: ${{ matrix.service }}
      namespace: ${{ inputs.branch_name || github.head_ref || github.ref_name }}
      cluster_name: development
    secrets: inherit

  comment_pr:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    needs: build_and_deploy_adhoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/repo-warm-up

      - name: Comment PR
        uses: ./.github/actions/comment-pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Service URLs"
          message: |
            [Core](${{ needs.build_and_deploy_adhoc.outputs.full_service_url }})

      # - name: Deploy to Kubernetes
      #   run: |
      #     helmfile sync -f kubernetes/helmfile.yaml \
      #       --environment=${{ inputs.environment }} \
      #       --namespace=${{ inputs.namespace }} \
      #       -l app=${{ inputs.service_name }} \
      #       --set ingress.host=${{ inputs.namespace }}-${{ inputs.service_name }}.${{ inputs.environment }}.postrix.io
      
