name: Build and push docker image

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        description: 'The name of the service to build and push'
        type: string
      latest_tag:
        required: false
        description: 'Whether to use the latest tag'
        type: boolean
        default: false

jobs:
  build_and_push:
    runs-on: ubuntu-latest-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Repo Warm Up
        id: repo_warm_up
        uses: ./.github/actions/repo-warm-up

      - name: Configure AWS credentials
        uses: ./.github/actions/aws-warm-up

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          TAGS="-t yuvadius/${{ inputs.service_name }}:${{ steps.repo_warm_up.outputs.git_hash }}"
          if [ "${{ inputs.latest_tag }}" = "true" ]; then
            TAGS="$TAGS -t yuvadius/${{ inputs.service_name }}:latest"
          fi
          docker build $TAGS -f services/${{ inputs.service_name }}/Dockerfile .
  
      - name: Push Docker image
        run: |
          docker push yuvadius/${{ inputs.service_name }} --all-tags
