name: Build and deploy adhoc

on:
  workflow_dispatch:
  pull_request:

jobs:
  build_and_push:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        service: [joby, capish, cannon]

    uses: ./.github/workflows/build-and-push.yml
    with:
      service_name: ${{ matrix.service }}
    secrets: inherit

  deploy:
    needs: build_and_push

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      environment_label: adhoc
      comment_pr: ${{ github.event_name != 'workflow_dispatch' }}
    secrets: inherit
