name: Build and deploy adhoc

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: 'The branch name of the adhoc deployment'
        type: string
  pull_request:

jobs:
  build_and_deploy_adhoc:
    uses: YuvalGlizerin/Postrix/.github/workflows/build-and-deploy.yml@main
    with:
      environment: dev
      service_name: core
      service_url: ${{ inputs.branch_name || github.head_ref || github.ref_name }}-core
    secrets: inherit

  comment_pr:
    runs-on: ubuntu-latest
    needs: build_and_deploy_adhoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Comment PR
        uses: ./.github/actions/comment-pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Service URLs"
          message: |
            [Core](https://example.com)"
