name: Build and deploy main to prod/sandbox

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Terraform Apply"]
  #   types:
  #     - completed

jobs:
  build_and_deploy_main:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        include:
          - { target: dev, service: core, cluster_name: development }
          - { target: prod, service: core, cluster_name: production }
    
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: ${{ matrix.target }}
      service_name: ${{ matrix.service }}
      namespace: ${{ matrix.target }}
      cluster_name: ${{ matrix.cluster_name }}
    secrets: inherit
