name: Build and deploy adhoc

on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: 'The branch name of the adhoc deployment'
        type: string
  # pull_request:

jobs:
  build_and_deploy_adhoc:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        service: [core]

    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: dev
      service_name: ${{ matrix.service }}
      service_url: ${{ inputs.branch_name || github.head_ref || github.ref_name }}-${{ matrix.service }}
    secrets: inherit

  comment_pr:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    needs: build_and_deploy_adhoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/repo-warm-up

      - name: Comment PR
        uses: ./.github/actions/comment-pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Service URLs"
          message: |
            [Core](${{ needs.build_and_deploy_adhoc.outputs.full_service_url }})
