name: Build and push docker image

permissions:
  contents: read
  id-token: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'The environment to deploy to(dev, prod)'
        type: string
      namespace:
        required: false
        description: 'The namespace to deploy to, defaults to adhoc namespace'
        type: string
      namespace_label:
        required: false
        description: 'The label to attach to the namespace, defaults to no label'
        type: string
        default: ''
      comment_pr:
        required: false
        description: 'Whether to comment on the PR with the service adhoc URLs, defaults to false'
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Repo Warm Up
        id: repo_warm_up
        uses: ./.github/actions/repo-warm-up

      - name: Configure AWS credentials
        uses: ./.github/actions/aws-warm-up
        with:
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Deploy to Kubernetes
        run: |
          helmfile sync -f kubernetes/helmfile.yaml \
          -l group=app \
          --wait --timeout 60 \
          --environment=${{ inputs.environment }} \
          --namespace=${{ inputs.namespace || steps.repo_warm_up.outputs.adhoc_namespace }} \
          --set postrixImage.tag=${{ steps.repo_warm_up.outputs.git_hash }}

      - name: Label namespace
        if: ${{ inputs.namespace_label }}
        run: |
          kubectl label namespace ${{ inputs.namespace || steps.repo_warm_up.outputs.adhoc_namespace }} environment=${{ inputs.namespace_label }}

      - name: Comment PR
        if: ${{ inputs.comment_pr }}
        uses: ./.github/actions/comment-pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Service URLs"
          message: |
            [Joby](https://${{ steps.repo_warm_up.outputs.adhoc_namespace }}-joby.postrix.io)
            [Capish](https://${{ steps.repo_warm_up.outputs.adhoc_namespace }}-capish.postrix.io)
            [Cannon](https://${{ steps.repo_warm_up.outputs.adhoc_namespace }}-cannon.postrix.io)
