name: Build and Push to Artifact Registry

on:
    workflow_run:
      workflows: ["Terraform Apply"]
      types:
        - completed

env:
  REGION: us-central1

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - { name: 'production', project_id: 'postrix', artifact_repo: 'production-docker' }
          - { name: 'development', project_id: 'postrix-development', artifact_repo: 'development-docker' }

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: ./.github/actions/gcp-warm-up
      with:
        project_id: ${{ matrix.environment.project_id }}
        region: ${{ env.REGION }}
        configure-docker: true
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        
    - name: Build Docker image
      run: |
        docker build -t $REGION-docker.pkg.dev/${{ matrix.environment.project_id }}/${{ matrix.environment.artifact_repo }}/core:latest ./services/core

    - name: Push Docker image to Google Artifact Registry
      run: |
        docker push $REGION-docker.pkg.dev/${{ matrix.environment.project_id }}/${{ matrix.environment.artifact_repo }}/core:latest
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy core-service \
        --image=$REGION-docker.pkg.dev/${{ matrix.environment.project_id }}/${{ matrix.environment.artifact_repo }}/core:latest \
        --region=$REGION \
        --platform=managed \
        --allow-unauthenticated
