name: Destroy PR resources

on:
  pull_request:
    types:
      - closed

env:
  REGION: us-central1
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  SERVICE_NAME: ${{ github.head_ref }}-core-service

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: postrix-development

    - name: Install gcloud beta components
      run: gcloud components install beta

    - name: Destroy resources
      run: |
        gcloud run services delete ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --platform=managed --quiet
        gcloud artifacts docker images delete ${{ env.REGION }}-docker.pkg.dev/postrix-development/development-docker/${{ env.BRANCH_NAME }}-core --quiet
    
    - name: Get branch url
      id: brach-url
      uses: efiShtain/urlify-string@v1.1
      with:
        string: ${{ env.BRANCH_NAME }}

    - name: Delete domain mapping
      run: |
        if gcloud beta run domain-mappings describe --service ${{ env.BRANCH_NAME }}-core-service --domain ${{ steps.brach-url.outputs.urlified-string }}.core.dev.postrix.io --region $REGION; then
          gcloud beta run domain-mappings delete --service ${{ env.BRANCH_NAME }}-core-service --domain ${{ steps.brach-url.outputs.urlified-string }}.core.dev.postrix.io --region $REGION
        fi