name: Destroy all adhoc namespaces on Sunday

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'  # Every Sunday at 06:00 UTC

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/repo-warm-up
        id: repo_warm_up

      - name: Configure AWS credentials
        uses: ./.github/actions/aws-warm-up

      - name: Delete dev environments
        run: |
          echo "Get all namespaces with label environment=adhoc"
          ADHOC_NAMESPACES=$(kubectl get namespaces -l environment=adhoc -o jsonpath='{.items[*].metadata.name}')
          
          for namespace in $ADHOC_NAMESPACES; do
            echo "Deleting namespace: $namespace"
            kubectl delete namespace $namespace
          done
