name: Job Notifications

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Repo Warm Up
        id: repo_warm_up
        uses: ./.github/actions/repo-warm-up

      - name: Configure AWS credentials
        uses: ./.github/actions/aws-warm-up

      - name: Build Docker image
        run: docker build -t yuvadius/job-notifications:latest -f .github/actions/job-notifications/Dockerfile .

      - name: Run container
        run: docker run -e KUBECONFIG=/kubeconfig -v ~/.kube/config:/kubeconfig -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          yuvadius/job-notifications:latest

      # - name: Run job-notifications action
      #   uses: ./.github/actions/job-notifications
